---
name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**

jobs:
  checkouts:
    name: Explorer
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.dump.outputs.matrix}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Directory Dump
        id: dump
        run: echo "files_list=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    needs: checkouts
    strategy:
      matrix:
        function:
          - execute_rest_extractor
          - oee_timeseries
        deploy-all-functions:
          - common
        environment:
          - test
          - prod

    steps:
      - name: Print actions stuff
        # if: ${{ contains(needs.checkouts.outputs.matrix.files_list, 'execute_rest_extractor') }}
        run: echo ${{ needs.checkouts.outputs.matrix.files_list }}
