---
name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**

jobs:
  checkouts:
    name: Strategy Builder
    runs-on: ubuntu-latest
    outputs:
        files_list: ${{ steps.dump.outputs.files_list }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Directory Dump
        id: dump
        run: echo "files_list=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      - name: Sanity Check
        run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs
  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    needs: checkouts
    strategy:
      matrix:
        # function:
        #   - execute_rest_extractor
        #   - oee_timeseries
        deploy-all-functions:
          - common
          - .github/workflows/test-deploy.yaml
        # environment:
        #   - test
        #   - prod
    steps:
      - name: print files_list
        run: echo "${{ needs.checkouts.outputs.files_list }}"
      - name: Deploy all
        if: contains(needs.checkouts.outputs.files_list, matrix.deploy-all-functions)
        run: echo "Contains ${{ matrix.deploy-all-functions }}"
