name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [idk]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**
    # outputs:
    #   strat-matrix:
    #     environment:
    #       description: List of environments to deploy to.
    #       value: ${{ ['prod', 'test'] }}

jobs:
  strategy-builder:
    name: Strategy Builder
    runs-on: ubuntu-latest
    outputs:
      functions: $ {{ steps.create_function_list.outputs.FUNCTIONS }}
        # strategy-matrix: ${{ steps.get-matrix.outputs.MATRIX }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # - name: Deploy All Check
      #   run: echo "DEPLOY_ALL=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} -- .github/workflows/test-deploy.yaml functions/common | xargs)"
      # - name: Only Matrix
      #   id: get-matrix
      #   run: |
      #     FUNCTIONS=$(find functions/*/ -path functions/common/ -prune -o -maxdepth 0 -type d -exec basename {} \;)
      #     echo MATRIX=$(jq -n --arg inarr "${FUNCTIONS}" '{ function: $inarr | split("\n") }') >> $GITHUB_OUTPUT
      - name: Build Strategy Matrix
        id: create_function_list
        run: |
          {
            echo "FUNCTIONS<<EOF
            test -n "$(git diff --name-only -- .github/workflows/test-deploy.yaml functions/common | xargs)" && find functions/*/ -not -path functions/common/ -maxdepth 0 -type d | cut -d / -f 2 | jq -sR '[split("\n")[]|select(.|length>0)]' || git diff --name-only functions/ | cut -d / -f 2 | jq -sR '[split("\n")[]|select(.|length>0)]'
            echo EOF
          } >> "$GITHUB_OUTPUT"
  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    needs: strategy-builder
    # strategy:
      # matrix:
        # function:
        #   - execute_rest_extractor
        #   - oee_timeseries
        # deploy-all-functions:
          # - common
          # - .github/workflows/test-deploy.yaml
        # environment:
        #   - test
        #   - prod
    steps:
      - name: print files_list
        run: echo '${{ fromJson(needs.strategy-builder.outputs.functions) }}'
