---
name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**

jobs:
  one:
    name: Explorer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Directory Dump
        run: git diff --name-only ${{ github.event.after }} ${{ github.event.before }}

  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - execute_rest_extractor
          - oee_timeseries
        deploy-all-functions:
          - common
        environment:
          - test
          - prod

    steps:
      - name: Print actions stuff
        run: echo ${{ matrix.environment }} ${{ matrix.function }} ${{ matrix.deploy-all-functions }}
