---
name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**

jobs:
  checkouts:
    name: Explorer
    runs-on: ubuntu-latest
    outputs: ${{ fromJSON(steps.dump.outputs.matrix) }}
      # files_list: ${{ steps.dump.outputs.files_list }}
      # idk: ${{ steps.idk.outputs.idk }}
      # idk2: ${{ steps.idk2.outputs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Directory Dump
        id: dump
        run: echo "files_list=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      # - name: idk
      #   id: idk
      #   run: echo "idk=123" >> $GITHUB_OUTPUT
      # - name: idk2
      #   id: idk2
      #   run: git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs

  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    needs: checkouts
    strategy:
      matrix:
        function:
          - execute_rest_extractor
          - oee_timeseries
        deploy-all-functions:
          - common
        environment:
          - test
          - prod

    steps:
      # - name: Print actions stuff
        # if: ${{ contains(needs.checkouts.outputs.matrix.files_list, 'execute_rest_extractor') }}
      - name: print idk
        run: echo ${{ needs.checkouts.outputs.matrix.idk }}
      - name: print files_list
        run: echo ${{ needs.checkouts.outputs.matrix.files_list }}
