---
name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**

jobs:
  one:
    name: Explorer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - execute_rest_extractor
          - oee_timeseries
        deploy-all-functions:
          - common
        environment:
          - test
          - prod

    steps:
      - name: Print actions stuff
        run: echo ${{ matrix.environment }} ${{ matrix.function }} ${{ matrix.deploy-all-functions }}
      - name: Print differently
        env:
          ENVIRO: ${{ matrix.environment }}
          FUNC: ${{ matrix.function }}
          DEPLOY_ALL: ${{ matrix.deploy-all-functions }}
        run: echo "$ENVIRO" "$FUNC" "$DEPLOY_ALL"
