---
name: Deploy Functions to CDF project using OIDC
on:
  push:
    branches: [main]
    paths:
      - .github/workflows/test-deploy.yaml
      - functions/**
    inputs:
      functions:
        required: true
          default: "['execute_rest_extractor','oee_timeseries']"
          

jobs:
  strategy-builder:
    name: Strategy Builder
    runs-on: ubuntu-latest
    outputs:
        files_list: ${{ steps.dump.outputs.files_list }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Directory Dump
        id: dump
        run: echo "files_list=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
      - name: Deploy All Check
        run: echo "DEPLOY_ALL=$(git diff --name-only -- .github common | xargs)"
      - name: test deploy all
        if: echo $DEPLOY_ALL
        run: echo "YES DEPLOY ALL"
  deploy:
    name: Deploy to Cognite Functions
    runs-on: ubuntu-latest
    needs: strategy-builder
    strategy:
      matrix:
        # functions:
        #   - execute_rest_extractor
        #   - oee_timeseries
        deploy-all-functions:
          - common
          - .github/workflows/test-deploy.yaml
        # environment:
        #   - test
        #   - prod
    steps:
      - name: print files_list
        run: echo "${{ needs.strategy-builder.outputs.files_list }}"
      - name: Deploy all
        if: contains(needs.strategy-builder.outputs.files_list, matrix.deploy-all-functions)
        run: echo "Contains ${{ matrix.deploy-all-functions }}"
